/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horseracing;

import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JPanel;

/**
 *
 * @author lammer
 */
public class Painel extends JPanel {
    
    public Painel() {
        initComponents();
        /*Seta os valores fa cabela de cada cavalo*/
        Core nucle = new Core();
        ArrayList premios = nucle.getPremioByCavalos();
        ap_um.setText(""+premios.get(0));
        ap_dois.setText(""+premios.get(1));
        ap_tres.setText(""+premios.get(2));
        ap_quatro.setText(""+premios.get(3));
        ap_sinco.setText(""+premios.get(4));
        ap_seis.setText(""+premios.get(5));
        ap_sete.setText(""+premios.get(6));
        ap_oito.setText(""+premios.get(7));
        ap_nove.setText(""+premios.get(8));
        ap_dez.setText(""+premios.get(9));
        
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("cavaloloko?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tickets t WHERE t.id NOT IN (SELECT ap.ticketId FROM Ticketofaposta ap)");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ptCvUmLabel = new javax.swing.JLabel();
        ptCvDoisLabel = new javax.swing.JLabel();
        ptCvTresLabel = new javax.swing.JLabel();
        ptCvQuatroLabel = new javax.swing.JLabel();
        ptCvSincoLabel = new javax.swing.JLabel();
        ptCvSeisLabel = new javax.swing.JLabel();
        ptCvSeteLabel = new javax.swing.JLabel();
        ptCvOitoLabel = new javax.swing.JLabel();
        ptCvNoveLabel = new javax.swing.JLabel();
        ptCvDezLabel = new javax.swing.JLabel();
        ptCvUmField = new javax.swing.JTextField();
        ptCvDoisField = new javax.swing.JTextField();
        ptCvTresField = new javax.swing.JTextField();
        ptCvQuatroField = new javax.swing.JTextField();
        ptCvSincoField = new javax.swing.JTextField();
        ptCvSeisField = new javax.swing.JTextField();
        ptCvSeteField = new javax.swing.JTextField();
        ptCvOitoField = new javax.swing.JTextField();
        ptCvNoveField = new javax.swing.JTextField();
        ptCvDezField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vt_um = new javax.swing.JLabel();
        vt_dois = new javax.swing.JLabel();
        vt_tres = new javax.swing.JLabel();
        vt_quatro = new javax.swing.JLabel();
        vt_sinco = new javax.swing.JLabel();
        vt_seis = new javax.swing.JLabel();
        vt_sete = new javax.swing.JLabel();
        vt_oito = new javax.swing.JLabel();
        vt_nove = new javax.swing.JLabel();
        vt_dez = new javax.swing.JLabel();
        ap_um = new javax.swing.JLabel();
        ap_dois = new javax.swing.JLabel();
        ap_tres = new javax.swing.JLabel();
        ap_quatro = new javax.swing.JLabel();
        ap_sinco = new javax.swing.JLabel();
        ap_seis = new javax.swing.JLabel();
        ap_sete = new javax.swing.JLabel();
        ap_oito = new javax.swing.JLabel();
        ap_nove = new javax.swing.JLabel();
        ap_dez = new javax.swing.JLabel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setMaximumSize(getMaximumSize());
        setMinimumSize(getMaximumSize());
        setPreferredSize(getMaximumSize());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        saveButton.setText("Iniciar Corrida");
        saveButton.addActionListener(formListener);
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 260, 60));

        deleteButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        deleteButton.setText("Excluir Aposta");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 250, 60));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        ptCvUmLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvUmLabel.setText("1");

        ptCvDoisLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvDoisLabel.setText("2");

        ptCvTresLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvTresLabel.setText("3");

        ptCvQuatroLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvQuatroLabel.setText("4");

        ptCvSincoLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvSincoLabel.setText("5");

        ptCvSeisLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvSeisLabel.setText("6");

        ptCvSeteLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvSeteLabel.setText("7");

        ptCvOitoLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvOitoLabel.setText("8");

        ptCvNoveLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvNoveLabel.setText("9");

        ptCvDezLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ptCvDezLabel.setText("10");

        ptCvUmField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvUm}"), ptCvUmField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvUmField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvDoisField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvDois}"), ptCvDoisField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvDoisField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvTresField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvTres}"), ptCvTresField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvTresField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvQuatroField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvQuatro}"), ptCvQuatroField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvQuatroField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvSincoField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvSinco}"), ptCvSincoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvSincoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvSeisField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvSeis}"), ptCvSeisField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvSeisField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvSeteField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvSete}"), ptCvSeteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvSeteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvOitoField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvOito}"), ptCvOitoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvOitoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvNoveField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvNove}"), ptCvNoveField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvNoveField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ptCvDezField.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ptCvDez}"), ptCvDezField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ptCvDezField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        newButton.setText("Novo Ticket");
        newButton.addActionListener(formListener);

        refreshButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        refreshButton.setText("Atualizar Lista");
        refreshButton.addActionListener(formListener);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Cavalo");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Apostas");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Vitórias");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Máx\\Aposta");

        vt_um.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_um.setText("0");

        vt_dois.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_dois.setText("0");

        vt_tres.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_tres.setText("0");

        vt_quatro.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_quatro.setText("0");

        vt_sinco.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_sinco.setText("0");

        vt_seis.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_seis.setText("0");

        vt_sete.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_sete.setText("0");

        vt_oito.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_oito.setText("0");

        vt_nove.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_nove.setText("0");

        vt_dez.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        vt_dez.setText("0");

        ap_um.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_um.setText("1");

        ap_dois.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_dois.setText("1");

        ap_tres.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_tres.setText("1");

        ap_quatro.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_quatro.setText("1");

        ap_sinco.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_sinco.setText("1");

        ap_seis.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_seis.setText("1");

        ap_sete.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_sete.setText("1");

        ap_oito.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_oito.setText("1");

        ap_nove.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_nove.setText("1");

        ap_dez.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ap_dez.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ptCvUmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvDoisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvTresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvQuatroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSincoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSeisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSeteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvOitoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvNoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvDezLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ptCvNoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptCvDezField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ptCvUmField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvDoisField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvTresField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvQuatroField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSincoField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSeisField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvSeteField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptCvOitoField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_sinco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_dez, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ap_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_dez, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_um, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_sinco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvUmLabel)
                    .addComponent(ptCvUmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_um)
                    .addComponent(ap_um))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvDoisLabel)
                    .addComponent(ptCvDoisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_dois)
                    .addComponent(ap_dois))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvTresLabel)
                    .addComponent(ptCvTresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_tres)
                    .addComponent(ap_tres))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvQuatroLabel)
                    .addComponent(ptCvQuatroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_quatro)
                    .addComponent(ap_quatro))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvSincoLabel)
                    .addComponent(ptCvSincoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_sinco)
                    .addComponent(ap_sinco))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvSeisLabel)
                    .addComponent(ptCvSeisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_seis)
                    .addComponent(ap_seis))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvSeteLabel)
                    .addComponent(ptCvSeteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_sete)
                    .addComponent(ap_sete))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvOitoLabel)
                    .addComponent(ptCvOitoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_oito)
                    .addComponent(ap_oito))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvNoveLabel)
                    .addComponent(ptCvNoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_nove)
                    .addComponent(ap_nove))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptCvDezLabel)
                    .addComponent(ptCvDezField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt_dez)
                    .addComponent(ap_dez))
                .addGap(18, 18, 18)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 540));

        masterTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        masterTable.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        masterTable.setRowHeight(32);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Ticket");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvUm}"));
        columnBinding.setColumnName("Um");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvDois}"));
        columnBinding.setColumnName("Dois");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvTres}"));
        columnBinding.setColumnName("Tres");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvQuatro}"));
        columnBinding.setColumnName("Quatro");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvSinco}"));
        columnBinding.setColumnName("Sinco");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvSeis}"));
        columnBinding.setColumnName("Seis");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvSete}"));
        columnBinding.setColumnName("Sete");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvOito}"));
        columnBinding.setColumnName("Oito");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvNove}"));
        columnBinding.setColumnName("Nove");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ptCvDez}"));
        columnBinding.setColumnName("Dez");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);
        if (masterTable.getColumnModel().getColumnCount() > 0) {
            masterTable.getColumnModel().getColumn(0).setResizable(false);
            masterTable.getColumnModel().getColumn(1).setMinWidth(70);
            masterTable.getColumnModel().getColumn(2).setMinWidth(70);
            masterTable.getColumnModel().getColumn(3).setMinWidth(70);
            masterTable.getColumnModel().getColumn(4).setMinWidth(70);
            masterTable.getColumnModel().getColumn(5).setMinWidth(70);
            masterTable.getColumnModel().getColumn(6).setMinWidth(70);
            masterTable.getColumnModel().getColumn(7).setMinWidth(70);
            masterTable.getColumnModel().getColumn(8).setMinWidth(70);
            masterTable.getColumnModel().getColumn(10).setMinWidth(70);
        }

        add(masterScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 850, 510));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Horse-racing-2.jpg"))); // NOI18N
        jLabel5.setText("@Clan Software");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                Painel.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                Painel.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                Painel.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                Painel.this.refreshButtonActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<horseracing.Tickets> toRemove = new ArrayList<horseracing.Tickets>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            horseracing.Tickets t = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            entityManager.remove(t);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        horseracing.Tickets t = new horseracing.Tickets();
        entityManager.persist(t);
        list.add(t);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
            //Faz a operação de calculo do ganhador
            Core lotCore = new Core();
            int win = lotCore.calculaGanhador(list);
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<horseracing.Tickets> merged = new ArrayList<horseracing.Tickets>(list.size());
            for (horseracing.Tickets t : list) {
                merged.add(entityManager.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap_dez;
    private javax.swing.JLabel ap_dois;
    private javax.swing.JLabel ap_nove;
    private javax.swing.JLabel ap_oito;
    private javax.swing.JLabel ap_quatro;
    private javax.swing.JLabel ap_seis;
    private javax.swing.JLabel ap_sete;
    private javax.swing.JLabel ap_sinco;
    private javax.swing.JLabel ap_tres;
    private javax.swing.JLabel ap_um;
    private javax.swing.JButton deleteButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.util.List<horseracing.Tickets> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField ptCvDezField;
    private javax.swing.JLabel ptCvDezLabel;
    private javax.swing.JTextField ptCvDoisField;
    private javax.swing.JLabel ptCvDoisLabel;
    private javax.swing.JTextField ptCvNoveField;
    private javax.swing.JLabel ptCvNoveLabel;
    private javax.swing.JTextField ptCvOitoField;
    private javax.swing.JLabel ptCvOitoLabel;
    private javax.swing.JTextField ptCvQuatroField;
    private javax.swing.JLabel ptCvQuatroLabel;
    private javax.swing.JTextField ptCvSeisField;
    private javax.swing.JLabel ptCvSeisLabel;
    private javax.swing.JTextField ptCvSeteField;
    private javax.swing.JLabel ptCvSeteLabel;
    private javax.swing.JTextField ptCvSincoField;
    private javax.swing.JLabel ptCvSincoLabel;
    private javax.swing.JTextField ptCvTresField;
    private javax.swing.JLabel ptCvTresLabel;
    private javax.swing.JTextField ptCvUmField;
    private javax.swing.JLabel ptCvUmLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel vt_dez;
    private javax.swing.JLabel vt_dois;
    private javax.swing.JLabel vt_nove;
    private javax.swing.JLabel vt_oito;
    private javax.swing.JLabel vt_quatro;
    private javax.swing.JLabel vt_seis;
    private javax.swing.JLabel vt_sete;
    private javax.swing.JLabel vt_sinco;
    private javax.swing.JLabel vt_tres;
    private javax.swing.JLabel vt_um;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
/*
  
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new Painel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                frame.pack();
                frame.setSize(1400, 1900);
                frame.setVisible(true);
            }
        });
        
        */
    }
    
}
